# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7759cc10ebf22f6e44081fb2b69f2c2457d8eb70f0933006323a53b45b4edaeeee1696dd4bb9b4ba05937033690309d5a93e3389d92a3a56dc1aa2f679c601d3

test:
  secret_key_base: 621a6f043b9b659e570f82e218035be55d9d3ee77dc6ca812c9ea499c604622266e55187acb4294fc9cec2cb5361cca88611cfad750aaaf2f6934e473a9df946

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
